#!/bin/bash

# Define variables
BACKUP_DIR="/home/user/backup"
SOURCE_DIR="/home/user/data"
BACKUP_FILE="backup-$(date +"%Y-%m-%d").tar.gz"
PASSWORD_FILE="/home/user/password.txt"

# Define functions
create_backup() {
  # Create a tarball of the source directory
  tar czf "$BACKUP_DIR/$BACKUP_FILE" "$SOURCE_DIR"
}

encrypt_backup() {
  # Encrypt the backup file with openssl
  openssl aes-256-cbc -a -salt -in "$BACKUP_DIR/$BACKUP_FILE" -out "$BACKUP_DIR/$BACKUP_FILE.enc" -pass file:"$PASSWORD_FILE"
  # Remove the unencrypted backup file
  rm "$BACKUP_DIR/$BACKUP_FILE"
}

# Main program
create_backup
encrypt_backup
